
services:
  qr-app:
    image: php:8.1-apache
    container_name: qr-app
    volumes:
      - ./src/qr-app:/var/www/html
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - mysql

  scan-page:
    build:
      context: .
      dockerfile: ./docker/scan-page/Dockerfile
    container_name: scan-page
    volumes:
      - ./src/scan-page/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  oqg-email:
    build:
      context: .
      dockerfile: ./docker/oqg-email/Dockerfile
    container_name: oqg-email
    volumes:
      - ./src/oqg-email/:/var/www/html/
    ports:
      - "8001:8001"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8001
    depends_on:
      - mysql

  oqg-content:
    build:
      context: .
      dockerfile: ./docker/oqg-content/Dockerfile
    container_name: oqg-content
    volumes:
      - ./src/oqg-content/:/var/www/html/
    ports:
      - "8002:8002"
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8002
 

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
